"""Generic WebSocket event definitions."""

from __future__ import annotations

from enum import Enum


class WSEventType(str, Enum):
    """All real-time event types emitted across Mirage channels."""

    CONSENT_REQUESTED = "CONSENT_REQUESTED"
    CONSENT_APPROVED = "CONSENT_APPROVED"
    CONSENT_DECLINED = "CONSENT_DECLINED"
    CONSENT_REVOKED = "CONSENT_REVOKED"
    CONSULTATION_STARTED = "CONSULTATION_STARTED"
    CONSULTATION_COMPLETED = "CONSULTATION_COMPLETED"
    TIMELINE_UPDATED = "TIMELINE_UPDATED"
    RECORD_UPDATED = "RECORD_UPDATED"
    AI_RESPONSE_READY = "AI_RESPONSE_READY"
    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"
    DASHBOARD_UPDATED = "DASHBOARD_UPDATED"
    
    # Appointment booking events
    APPOINTMENT_CREATED = "APPOINTMENT_CREATED"
    APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED"
    APPOINTMENT_CANCELLED = "APPOINTMENT_CANCELLED"
    APPOINTMENT_REMINDER = "APPOINTMENT_REMINDER"
    EMERGENCY_APPOINTMENT = "EMERGENCY_APPOINTMENT"
    CONSULTATION_READY = "CONSULTATION_READY"
    DOCTOR_SCHEDULE_UPDATED = "DOCTOR_SCHEDULE_UPDATED"
    DOCTOR_TIME_OFF_ADDED = "DOCTOR_TIME_OFF_ADDED"
