"""Add appointment booking system

Revision ID: 20260709_add_appointment_booking
Revises: d9478b961bc5
Create Date: 2026-07-09

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260709_add_appointment_booking'
down_revision = 'd9478b961bc5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add columns to doctors table
    op.add_column('doctors', sa.Column('max_daily_appointments', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('is_accepting_appointments', sa.Boolean(), nullable=True))
    op.add_column('doctors', sa.Column('next_available_date', sa.Date(), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE doctors SET max_daily_appointments = 20")
    op.execute("UPDATE doctors SET is_accepting_appointments = TRUE")
    
    # Make columns non-nullable after setting defaults
    op.alter_column('doctors', 'max_daily_appointments', nullable=False)
    op.alter_column('doctors', 'is_accepting_appointments', nullable=False)
    
    # 2. Create appointments table
    op.create_table('appointments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('patient_id', sa.UUID(), nullable=False),
        sa.Column('facility_id', sa.UUID(), nullable=False),
        sa.Column('doctor_id', sa.UUID(), nullable=True),
        sa.Column('visit_id', sa.UUID(), nullable=True),
        sa.Column('appointment_date', sa.Date(), nullable=False),
        sa.Column('desired_duration_minutes', sa.Integer(), nullable=True),
        sa.Column('allocated_start_time', sa.Time(), nullable=True),
        sa.Column('allocated_end_time', sa.Time(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('symptoms', sa.Text(), nullable=True),
        sa.Column('priority', sa.String(length=20), nullable=True),
        sa.Column('is_emergency', sa.Boolean(), nullable=True),
        sa.Column('triage_score', sa.Integer(), nullable=True),
        sa.Column('preferred_doctor_id', sa.UUID(), nullable=True),
        sa.Column('patient_confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('doctor_confirmed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cancelled_by', sa.String(length=20), nullable=True),
        sa.Column('cancellation_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], onupdate='CASCADE', ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['preferred_doctor_id'], ['doctors.id'], onupdate='CASCADE', ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], onupdate='CASCADE', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_date', 'appointments', ['appointment_date'], unique=False)
    op.create_index('ix_appointments_doctor_id', 'appointments', ['doctor_id'], unique=False)
    op.create_index('ix_appointments_facility_id', 'appointments', ['facility_id'], unique=False)
    op.create_index('ix_appointments_patient_id', 'appointments', ['patient_id'], unique=False)
    op.create_index('ix_appointments_priority', 'appointments', ['priority'], unique=False)
    op.create_index('ix_appointments_status', 'appointments', ['status'], unique=False)
    
    # 3. Create doctor_schedules table
    op.create_table('doctor_schedules',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('doctor_id', sa.UUID(), nullable=False),
        sa.Column('day_of_week', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('is_working_day', sa.Boolean(), nullable=True),
        sa.Column('default_slot_duration', sa.Integer(), nullable=True),
        sa.Column('max_daily_appointments', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('doctor_id', 'day_of_week')
    )
    op.create_index('ix_doctor_schedules_doctor_id', 'doctor_schedules', ['doctor_id'], unique=False)
    
    # 4. Create doctor_time_offs table
    op.create_table('doctor_time_offs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('doctor_id', sa.UUID(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('requested_by', sa.UUID(), nullable=True),
        sa.Column('approved_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['requested_by'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_time_offs_dates', 'doctor_time_offs', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_doctor_time_offs_doctor_id', 'doctor_time_offs', ['doctor_id'], unique=False)
    
    # 5. Create appointment_slot_allocations table
    op.create_table('appointment_slot_allocations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('appointment_id', sa.UUID(), nullable=False),
        sa.Column('doctor_id', sa.UUID(), nullable=False),
        sa.Column('slot_date', sa.Date(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('buffer_after_minutes', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_slot_allocations_appointment', 'appointment_slot_allocations', ['appointment_id'], unique=False)
    op.create_index('ix_slot_allocations_doctor_date', 'appointment_slot_allocations', ['doctor_id', 'slot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slot_allocations_doctor_date', table_name='appointment_slot_allocations')
    op.drop_index('ix_slot_allocations_appointment', table_name='appointment_slot_allocations')
    op.drop_table('appointment_slot_allocations')
    
    op.drop_index('ix_doctor_time_offs_doctor_id', table_name='doctor_time_offs')
    op.drop_index('ix_doctor_time_offs_dates', table_name='doctor_time_offs')
    op.drop_table('doctor_time_offs')
    
    op.drop_index('ix_doctor_schedules_doctor_id', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    
    op.drop_index('ix_appointments_status', table_name='appointments')
    op.drop_index('ix_appointments_priority', table_name='appointments')
    op.drop_index('ix_appointments_patient_id', table_name='appointments')
    op.drop_index('ix_appointments_facility_id', table_name='appointments')
    op.drop_index('ix_appointments_doctor_id', table_name='appointments')
    op.drop_index('ix_appointments_date', table_name='appointments')
    op.drop_table('appointments')
    
    op.drop_column('doctors', 'next_available_date')
    op.drop_column('doctors', 'is_accepting_appointments')
    op.drop_column('doctors', 'max_daily_appointments')
    # ### end Alembic commands ###
